
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UsersManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PhotoRating
{

    public int Id { get; set; }

    public int PhotoId { get; set; }

    public int UserId { get; set; }

    public string Comment { get; set; }

    public int Rating { get; set; }

    public System.DateTime CreationDate { get; set; }



    public virtual Photo Photo { get; set; }

    public virtual User User { get; set; }

}

}
